### ISSUE TITLE
Documentation in english missing

### ISSUE THREAD

**Issue by psonnera** [yaronkhazai/gmns-bridge#1]
Fantastic idea. Can I build a wiki and share with CGM In The Coud?

**Comment by yaronkhazai** [comment]
Hi 

We are currently working on a English manual on how to run it (on free tire) on AWS

**Comment by yaronkhazai** [comment]
> Fantastic idea. Can I build a wiki and share with CGM In The Coud?

once it is ready, could i ask you to translate it to Italian?
