### ISSUE TITLE
Doesn't work if password starts with @

### ISSUE THREAD

**Issue by parapenT1sta** [yaronkhazai/gmns-bridge#3]
gmns-bridge wasn't working with password like **@Xxxxx.xxx** 
changed to **Xxxxx.xxxx** and worked right away :)

**Comment by yaronkhazai** [comment]
the config file is stored in YAML format
in this format you need to escape special characters
in order to have a password that starts with the @ sigh you should write it as \\@
so @Xxxxx.xxx should be \\@Xxxxx.xxx in the config file

**Comment by parapenT1sta** [comment]
> the config file is stored in YAML format
> in this format you need to escape special characters
> in order to have a password that starts with the @ sigh you should write is as @
> so @Xxxxx.xxx should be @Xxxxx.xxx in the config file

And it was in the config file :) Try your self to use a password starting with @ in Glucomen platform.
